name : CICD Database Dev to Prod


on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil konek gan"

            cd /home/wahyu/CICD_DATABASE
            echo "Berhasil Masuk ke folder gan"

            sudo docker compose up -d # Menjalankan docker compose di server
            echo "Berhasil menjalankan docker compose di server gan"